<?php /*

Copyright (c) 2008 Metathinking Ltd.

This file is part of Affiliates For All.

Affiliates For All is free software: you can redistribute it and/or
modify it under the terms of the GNU General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

Affiliates For All is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with Affiliates For All.  If not, see
<http://www.gnu.org/licenses/>.

*/ ?>

<div id="tabs" class="admin-panel overview-admin medium">
  <ul>
    <li><a href="#summary"><span><?php echo __('Summary') ?></span></a></li>
    <li><a href="#downloadpayments"><span><?php echo __('Download Payments File') ?></span></a></li>
    <li>
      <a href="#uploadpayments"><span><?php echo __('Upload Completed Payments') ?></span></a>
    </li>
  </ul>
  <div id="summary">
    <dl class="summary-list">
      <div class="summary-row">
        <dt><?php echo __('Total Orders:') ?></dt>
        <dd><?php echo $v->currency.$v->total_orders ?></dd>
      </div>
      <div class="summary-row">
        <dt><?php echo __('Total Commission:') ?></dt>
        <dd><?php echo $v->currency.$v->total_commission ?></dd>
      </div>
      <div class="summary-row">
        <dt><?php echo __('Commission Paid:') ?></dt>
        <dd><?php echo $v->currency.$v->total_payments ?></dd>
      </div>
      <div class="summary-row">
        <dt><?php echo __('Commission Payable:') ?></dt>
        <dd><?php echo $v->currency.$v->total_payable ?></dd>
      </div>
    </dl>
  </div>
  <div id="downloadpayments">
    <form method="post" class="admin-query-form">
      <div class="mb-3">
        <label class="form-label" for="to"><?php echo __('Download payments up to and including:') ?></label>
        <input id="to" class="form-control" type="date"/>
      </div>
      <div class="text-center">
        <input id="download" class="btn btn-primary" type="submit" value="<?php echo __('Download') ?>"/>
      </div>
    </form>
  </div>
  <div id="uploadpayments">
    <form method="post" enctype="multipart/form-data" class="admin-query-form">
      <div class="mb-3">
        <label class="form-label" for="payments_file"><?php echo __('Payments file:') ?></label>
        <input id="payments_file" class="form-control" type="file" name="file"/>
      </div>
      <div class="text-center">
        <input class="btn btn-primary" type="submit" value="<?php echo __('Upload') ?>"/>
      </div>
    </form>
  </div>
</div>

<?php echo $v->message ?>
