<?php /*

Copyright (c) 2008 Metathinking Ltd.

This file is part of Affiliates For All.

Affiliates For All is free software: you can redistribute it and/or
modify it under the terms of the GNU General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

Affiliates For All is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with Affiliates For All.  If not, see
<http://www.gnu.org/licenses/>.

*/ ?>

<div id="tabs" class="admin-panel order-admin vwide">
  <ul>
    <li><a href="#query"><span><?php echo __('Date Range') ?></span></a></li>
    <li><a href="#results"><span><?php echo __('Results') ?></span></a></li>
    <li><a href="#details"><span><?php echo __('Order Details') ?></span></a></li>
  </ul>
  <div id="query">
    <form method="post" class="admin-query-form">
      <div class="mb-3 row">
        <label class="col-sm-4 col-form-label" for="from"><?php echo __('View orders from:') ?></label>
        <div class="col-sm-8">
          <input id="from" class="form-control" type="text" size="12"/>
        </div>
      </div>
      <div class="mb-3 row">
        <label class="col-sm-4 col-form-label" for="to"><?php echo __('to:') ?></label>
        <div class="col-sm-8">
          <input id="to" class="form-control" type="text" size="12"/>
        </div>
      </div>
      <div class="text-center">
        <input id="display" class="btn btn-primary" type="submit" value="<?php echo __('Display') ?>"/>
        <input id="download" class="btn btn-secondary" type="submit" value="<?php echo __('Download') ?>"/>
      </div>
      <div id="addnew"><a href="#"><?php echo __('Add new') ?></a> <?php echo __('order') ?>.</div>
    </form>
  </div>
  <div id="results">
    <table id="restable" class="table table-striped table-bordered table-hover align-middle">
    </table>
    <div id="navigation">
      <?php echo __('Page') ?> <span id="currentpage">?</span> <?php echo __('of') ?> <span id="maxpages">?</span>.  <?php echo __('Go to:') ?>
      <a id="previous" href="#"><?php echo __('Previous Page') ?></a>,
      <a id="next" href="#"><?php echo __('Next Page') ?></a>,
      <?php echo __('Page') ?> <span id="pagelist">?</span>.
    </div>
  </div>
  <div id="details">
    <div id="detailstable" class="admin-details-form">
      <?php foreach($v->fields->get_field_descriptions() as $details) { ?>
        <div class="mb-3 row">
          <label class="col-sm-4 col-form-label" for="details_<?php echo $details[0] ?>">
            <?php echo $details[1] ?><?php echo $details[3] ? ' *' : '' ?>
          </label>
          <div class="col-sm-8">
            <?php $this->make_data_field($details) ?>
          </div>
        </div>
      <?php } ?>
      <div class="text-center">
        <input id="details_save" class="btn btn-primary" type="submit" value="<?php echo __('Save') ?>"/>
        <input id="details_cancel" class="btn btn-secondary" type="submit" value="<?php echo __('Cancel') ?>"/>
      </div>
    </div>
    <p>
		<?php 
			echo __('Fields marked') ;
			echo ' * '; 
			echo __('are required.');
		?>
	</p>
  </div>
</div>

<div id="offstart" class="dialogue" title="<?php echo __('No More Data') ?>"><?php echo __('You are already on the first page.') ?></div>
<div id="offend" class="dialogue" title="<?php echo __('No More Data') ?>"><?php echo __('You are already on the last page.') ?></div>
<div id="requiredfields" class="dialogue" title="<?php echo __('Required Fields Empty') ?>"><?php echo __('Please complete all required fields marked') ?> * </div>
<div id="dberror" class="dialogue" title="<?php echo __('Invalid Data') ?>">?</div>
<div id="saved" class="dialogue" title="<?php echo __('Changes Saved') ?>"><?php echo __('The information you entered has been saved.') ?></div>
<div id="confirmdelete" class="dialogue" title="<?php echo __('Are you sure?') ?>"><?php echo __('Are you sure you want to delete this record?') ?></div>
