<?php /*

Copyright (c) 2008 Metathinking Ltd.

This file is part of Affiliates For All.

Affiliates For All is free software: you can redistribute it and/or
modify it under the terms of the GNU General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

Affiliates For All is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with Affiliates For All.  If not, see
<http://www.gnu.org/licenses/>.

*/ ?>

<nav id="menu" class="nav justify-content-center flex-wrap gap-2">
  <?php if($this->admin) { ?>
    <a class="nav-link" href="admin-overview.php"><?php echo __('Site Overview') ?></a>
    <a class="nav-link" href="admin-affiliates.php"><?php echo __('Affiliates') ?></a>
    <a class="nav-link" href="admin-banners.php"><?php echo __('Banners') ?></a>
    <a class="nav-link" href="admin-orders.php"><?php echo __('All Orders') ?></a>
    <a class="nav-link" href="admin-payments.php"><?php echo __('All Payments') ?></a>
    <a class="nav-link" href="overview.php"><?php echo __('Back') ?></a>
  <?php } else { ?>
    <a class="nav-link" href="overview.php"><?php echo __('Overview') ?></a>
    <a class="nav-link" href="account.php"><?php echo __('Your Account') ?></a>

    <?php if($this->offer_banners) { ?>
      <a class="nav-link" href="banners.php"><?php echo __('Banners') ?></a>
    <?php } ?>
    
    <a class="nav-link" href="orders.php"><?php echo __('Your Orders') ?></a>
    <a class="nav-link" href="payments.php"><?php echo __('Your Payments') ?></a>

    <?php if($_SESSION['administrator']) { ?>
      <a class="nav-link" href="admin-overview.php"><?php echo __('Admin') ?></a>
    <?php } ?>
  <?php } ?>

  <a class="nav-link" href="logout.php"><?php echo __('Log Out') ?></a>
</nav>
