<?php /*

Copyright (c) 2026 Metathinking Ltd.

This file is part of Affiliates For All.

Affiliates For All is free software: you can redistribute it and/or
modify it under the terms of the GNU General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

Affiliates For All is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with Affiliates For All.  If not, see
<http://www.gnu.org/licenses/>.

*/ ?>

    <?php if($this->show_heading) { ?>
            </main>
            <footer id="powered" class="text-center small text-muted">
              <?php echo __('Powered by Affiliates for All') ?>
              ,
              <?php echo __('copyright') ?>
          
              © 2008 - <?php echo date('Y') ?> .
            </footer>
          </div>
        </div>
      </div>
    <?php } else { ?>
      <footer id="powered" class="text-center small text-muted mt-4">
        <?php echo __('Powered by Affiliates for All') ?>
        ,
        <?php echo __('copyright') ?>
    
        © 2008 - <?php echo date('Y') ?> .
      </footer>
    <?php } ?>
  </body>
</html>
